### ISSUE TITLE
Server starts correctly, but errors appear when I try to consult server URL

### ISSUE THREAD

**Issue by dzc34** [Orbitale/Rymfony#11]
Server starts correctly, but errors appear when I try to consult  server URL.

```bash
target/release/rymfony server:start --port 8989 
       # INFO - Starting PHP...
       # INFO - Running native PHP server with PID 15360
       # [Sun Aug  2 13:27:05 2020] PHP 7.4.8 Development Server (http://127.0.0.1:65535) started
       # INFO - PHP server is ready
       # INFO - PHP started with module CLI
       # INFO - Starting HTTP server...
       # INFO - Configured document root: /home/fabrice/Bureau/test_rymfony/rymfony
       # INFO - PHP entrypoint file: /home/fabrice/Bureau/test_rymfony/rymfony/index.php
       # INFO - Server listening to http://127.0.0.1:8989
```

# Error with `CURL`

```bash
curl -v http://127.0.0.1:8989
       # * Rebuilt URL to: http://127.0.0.1:8989/
       # *   Trying 127.0.0.1...
       # * TCP_NODELAY set
       # * Connected to 127.0.0.1 (127.0.0.1) port 8989 (#0)
       # > GET / HTTP/1.1
       # > Host: 127.0.0.1:8989
       # > User-Agent: curl/7.58.0
       # > Accept: */*
       # > 
       # * Empty reply from server
       # * Connection #0 to host 127.0.0.1 left intact
       # curl: (52) Empty reply from server
```
### Rymfony log
```bash
INFO - HTTP/1.1 GET /
[Sun Aug  2 13:29:34 2020] 127.0.0.1:36746 Accepted
[Sun Aug  2 13:29:34 2020] 127.0.0.1:36746 Invalid request (Malformed HTTP request)
[Sun Aug  2 13:29:34 2020] 127.0.0.1:36746 Closing
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error(Io(Custom { kind: UnexpectedEof, error: "failed to fill whole buffer" }), State { next_error: None, backtrace: InternalBacktrace { backtrace: None } })', src/http/fastcgi_handler.rs:82:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

# Error with Chormium
![Sélection_001](https://user-images.githubusercontent.com/6709977/89122334-a3816200-d4c6-11ea-9d76-609155ec9437.png)

### Rymfony log
```bash
INFO - HTTP/1.1 GET /
[Sun Aug  2 13:45:12 2020] 127.0.0.1:38894 Accepted
[Sun Aug  2 13:45:12 2020] 127.0.0.1:38894 Invalid request (Malformed HTTP request)
[Sun Aug  2 13:45:12 2020] 127.0.0.1:38894 Closing
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error(Io(Custom { kind: UnexpectedEof, error: "failed to fill whole buffer" }), State { next_error: None, backtrace: InternalBacktrace { backtrace: None } })', src/http/fastcgi_handler.rs:82:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
INFO - HTTP/1.1 GET /
[Sun Aug  2 13:45:12 2020] 127.0.0.1:38896 Accepted
[Sun Aug  2 13:45:12 2020] 127.0.0.1:38896 Invalid request (Malformed HTTP request)
[Sun Aug  2 13:45:12 2020] 127.0.0.1:38896 Closing
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error(Io(Custom { kind: UnexpectedEof, error: "failed to fill whole buffer" }), State { next_error: None, backtrace: InternalBacktrace { backtrace: None } })', src/http/fastcgi_handler.rs:82:18
INFO - HTTP/1.1 GET /
[Sun Aug  2 13:45:12 2020] 127.0.0.1:38900 Accepted
[Sun Aug  2 13:45:12 2020] 127.0.0.1:38900 Invalid request (Malformed HTTP request)
[Sun Aug  2 13:45:12 2020] 127.0.0.1:38900 Closing
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error(Io(Custom { kind: UnexpectedEof, error: "failed to fill whole buffer" }), State { next_error: None, backtrace: InternalBacktrace { backtrace: None } })', src/http/fastcgi_handler.rs:82:18

```

# Error with Firefox

![Sélection_002](https://user-images.githubusercontent.com/6709977/89122409-2dc9c600-d4c7-11ea-84ba-169e20b60eff.png)

### Rymfony log
```bash
INFO - HTTP/1.1 GET /
[Sun Aug  2 13:49:27 2020] 127.0.0.1:41150 Accepted
[Sun Aug  2 13:49:27 2020] 127.0.0.1:41150 Invalid request (Malformed HTTP request)
[Sun Aug  2 13:49:27 2020] 127.0.0.1:41150 Closing
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error(Io(Custom { kind: UnexpectedEof, error: "failed to fill whole buffer" }), State { next_error: None, backtrace: InternalBacktrace { backtrace: None } })', src/http/fastcgi_handler.rs:82:18
INFO - HTTP/1.1 GET /
[Sun Aug  2 13:49:27 2020] 127.0.0.1:41154 Accepted
[Sun Aug  2 13:49:27 2020] 127.0.0.1:41154 Invalid request (Malformed HTTP request)
[Sun Aug  2 13:49:27 2020] 127.0.0.1:41154 Closing
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error(Io(Custom { kind: UnexpectedEof, error: "failed to fill whole buffer" }), State { next_error: None, backtrace: InternalBacktrace { backtrace: None } })', src/http/fastcgi_handler.rs:82:18
INFO - HTTP/1.1 GET /
[Sun Aug  2 13:49:27 2020] 127.0.0.1:41158 Accepted
[Sun Aug  2 13:49:27 2020] 127.0.0.1:41158 Invalid request (Malformed HTTP request)
[Sun Aug  2 13:49:27 2020] 127.0.0.1:41158 Closing
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error(Io(Custom { kind: UnexpectedEof, error: "failed to fill whole buffer" }), State { next_error: None, backtrace: InternalBacktrace { backtrace: None } })', src/http/fastcgi_handler.rs:82:18
INFO - HTTP/1.1 GET /
[Sun Aug  2 13:49:27 2020] 127.0.0.1:41162 Accepted
[Sun Aug  2 13:49:27 2020] 127.0.0.1:41162 Invalid request (Malformed HTTP request)
[Sun Aug  2 13:49:27 2020] 127.0.0.1:41162 Closing
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error(Io(Custom { kind: UnexpectedEof, error: "failed to fill whole buffer" }), State { next_error: None, backtrace: InternalBacktrace { backtrace: None } })', src/http/fastcgi_handler.rs:82:18
INFO - HTTP/1.1 GET /
[Sun Aug  2 13:50:12 2020] 127.0.0.1:41530 Accepted
[Sun Aug  2 13:50:12 2020] 127.0.0.1:41530 Invalid request (Malformed HTTP request)
[Sun Aug  2 13:50:12 2020] 127.0.0.1:41530 Closing
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error(Io(Custom { kind: UnexpectedEof, error: "failed to fill whole buffer" }), State { next_error: None, backtrace: InternalBacktrace { backtrace: None } })', src/http/fastcgi_handler.rs:82:18
INFO - HTTP/1.1 GET /
[Sun Aug  2 13:50:12 2020] 127.0.0.1:41532 Accepted
[Sun Aug  2 13:50:12 2020] 127.0.0.1:41532 Invalid request (Malformed HTTP request)
[Sun Aug  2 13:50:12 2020] 127.0.0.1:41532 Closing
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error(Io(Custom { kind: UnexpectedEof, error: "failed to fill whole buffer" }), State { next_error: None, backtrace: InternalBacktrace { backtrace: None } })', src/http/fastcgi_handler.rs:82:18
INFO - HTTP/1.1 GET /
[Sun Aug  2 13:50:12 2020] 127.0.0.1:41536 Accepted
[Sun Aug  2 13:50:12 2020] 127.0.0.1:41536 Invalid request (Malformed HTTP request)
[Sun Aug  2 13:50:12 2020] 127.0.0.1:41536 Closing
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error(Io(Custom { kind: UnexpectedEof, error: "failed to fill whole buffer" }), State { next_error: None, backtrace: InternalBacktrace { backtrace: None } })', src/http/fastcgi_handler.rs:82:18
```
---------------------
additional information :

```bash
rymfony --version
       # rymfony 0.1

php -v
        # PHP 7.4.8 (cli)

composer --version
       # Composer 1.6.3 2018-01-31 16:28:17

cat /etc/os-release 
       # NAME="Ubuntu"
       # VERSION="18.04.4 LTS (Bionic Beaver)"

cargo --version
       # cargo 1.45.1 
```

**Comment by maitrepylos** [comment]
Same problem
```bash
sudo rymfony server:start --port 80
INFO - Starting PHP...
INFO - Running native PHP server with PID 10588
[Mon Aug  3 12:11:34 2020] PHP 7.4.7 Development Server (http://127.0.0.1:65535) started
INFO - PHP server is ready
INFO - PHP started with module CLI
INFO - Starting HTTP server...
INFO - Configured document root: /home/gg/Sites/datt/public/
INFO - PHP entrypoint file: /home/gg/Sites/datt/public/index.php
INFO - Server listening to http://127.0.0.1:80
INFO - HTTP/1.1 GET /
[Mon Aug  3 12:12:15 2020] 127.0.0.1:40138 Accepted
[Mon Aug  3 12:12:15 2020] 127.0.0.1:40138 Invalid request (Malformed HTTP request)
[Mon Aug  3 12:12:15 2020] 127.0.0.1:40138 Closing
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error(Io(Custom { kind: UnexpectedEof, error: "failed to fill whole buffer" }), State { next_error: None, backtrace: InternalBacktrace { backtrace: None } })', src/http/fastcgi_handler.rs:82:78
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
additional information :

```bash
rymfony --version
       # rymfony 0.1

php -v
        # PHP 7.4.7 (cli)

composer --version
       # Composer 1.10.1 2020-03-13 20:34:27

cat /etc/os-release 
      NAME="Linux Mint"
     VERSION="20 (Ulyana)"
      ID=linuxmint
ID_LIKE=ubuntu
PRETTY_NAME="Linux Mint 20"
VERSION_ID="20"
HOME_URL="https://www.linuxmint.com/"
SUPPORT_URL="https://forums.ubuntu.com/"
BUG_REPORT_URL="http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/"
PRIVACY_POLICY_URL="https://www.linuxmint.com/"
VERSION_CODENAME=ulyana
UBUNTU_CODENAME=focal

cargo --version
       #cargo 1.46.0-nightly (fede83ccf 2020-07-02)
```

**Comment by Pierstoval** [comment]
Thanks for reporting this issue!

I think it might come from the fact that the fastcgi handling is buffered instead of being streamed.

I have to make more research about this, since I'm using the [fastcgi_client](https://docs.rs/fastcgi-client/0.5.0/fastcgi_client/) crate and it doesn't seem to have an option to stream the output.

There are also issues with the same crate forcing me to parse the entire HTTP response as a string, which isn't viable in long-term, because this might be incompatible with binary responses or other edge cases I don't know yet.

**Comment by kevinpapst** [comment]
Likely fixed by #20 - as both reports mention the exact same error I had and both started CLI instead of FPM

**Comment by Pierstoval** [comment]
@dzc34, @maitrepylos , can you retry with the latest builds? It should be fixed 😉

**Comment by Pierstoval** [comment]
No answer for some time, and latest releases and refactorings may have fixed this. Feel free to reopen if you encounter this issue again 👍
